# Generated by Django 5.0.4 on 2024-05-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_dev', models.PositiveIntegerField()),
                ('prem_support_months', models.PositiveIntegerField()),
                ('free_updates_months', models.PositiveIntegerField()),
            ],
        ),
    ]
