# Generated by Django 5.0.4 on 2024-05-13 06:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landwind', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='desc',
            field=models.TextField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='num_dev',
            field=models.CharField(max_length=10),
        ),
    ]
