# Generated by Django 5.0.4 on 2024-05-13 10:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landwind', '0002_package_desc_alter_package_num_dev'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
